# Week 4 - Activities

Learning objectives:
1. Review discrete probability distribution
2. NumPy arrays and element-wise operations
3. Print strings with the method <code>format()</code>

## Case Study: A Newsvendor Problem (Array Version)
***Background***: In this case study, we will solve the previous newsvendor problem using NumPy arrays, in order to show the benefits of element-wise operations. The discrete probability distribution is again given as the following table.

| $ $ |probabilities|paper1|paper2|
|:----|:---------|:----------|:----------|
|Sunny| 0.315 | 560  | 533 | 
|Cloudy | 0.226 | 530 | 486 | 
|Raining | 0.289 | 389 | 386 | 
|Thunderstorm| 0.087 | 202 | 234 |
|Haze| 0.083 | 278 | 263 |

The table above is expressed by the two-dimensional NumPy array <code>distr</code>.

In [14]:
import numpy as np

distr = np.array([[0.315, 0.226, 0.289, 0.087, 0.083],
                  [560, 530, 389, 202, 278],
                  [533, 486, 386, 234, 263]])

distr

array([[3.15e-01, 2.26e-01, 2.89e-01, 8.70e-02, 8.30e-02],
       [5.60e+02, 5.30e+02, 3.89e+02, 2.02e+02, 2.78e+02],
       [5.33e+02, 4.86e+02, 3.86e+02, 2.34e+02, 2.63e+02]])

In this two-dimensional array, the first row represents the probabilities of all weather types, the second and the third rows are the demands of two newspapers under different weather conditions. 

### Task 1

Calculate the expected values of the demands of <code>paper1</code> and <code>paper2</code>. 

***Solution***: Recalling that the mean value is expressed as
$$
\mathbb{E}(D_{\text{paper}}) = \sum\limits_{s=1}^S p_s d_s
$$
where $p_s$ is the probability, and $d_{s}$ is the demand of <code>paper</code>, under weather $s$. 

In [15]:
sum(distr[0] * distr[1])

449.249

In [18]:
exp_d = np.sum(distr[0] * distr[1:], axis = 1)
exp_d

array([449.249, 431.472])

### Task 2
Calculate the standard deviation of paper demands, expressed as 
$$
\sigma_D = \sqrt{\sum\limits_{s=1}^S p_s (d_{s} - \mathbb{E}(D_{\text{paper}}))^2}
$$

***Solution***: 

The most convenient and practical way to calculate the standard deviations is to use the broadcasting of <code>NumPy</code> arrays. Please read this [chapter](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html) of the reference book to learn this technique.

In this chapter, you may need to use the method <code>reshape</code> of the array data object. Document of this method is given [here](https://numpy.org/doc/1.18/reference/generated/numpy.reshape.html).

In [36]:
(np.sum(distr[0]*(distr[1:] - exp_d.reshape(2,1))**2, axis=1))**0.5

array([118.90763222, 101.3157797 ])

### Task 3
Suppose that the costs of <code>paper1</code> and <code>paper2</code> are 0.6 and 0.8 dollars, and the selling prices of <code>paper1</code> and <code>paper2</code> are $\$1.00$ and $\$1.15$, respectively. Calculate the expected total profit if the newsboy has ordered 430 pieces of <code>paper1</code> and 380 pieces of <code>paper2</code>. 

**Solution**:

The expected sold quantities can be firstly calculated as an array.

In [38]:
price = np.array([[1],[1.15]])
price

array([[1.  ],
       [1.15]])

In [39]:
orders = np.array([[430],[380]])
orders

array([[430],
       [380]])

In [41]:
sales = np.minimum(distr[1:], orders)
sales

array([[430., 430., 389., 202., 278.],
       [380., 380., 380., 234., 263.]])

In [48]:
np.sum(distr[0]*sales, axis =1).reshape(2,1)

array([[385.699],
       [357.587]])

By using the array of expected sold quantities, the expected profit can also be calculated via broadcasting and element-wise operations.

In [50]:
profit = np.sum(distr[0]*sales, axis =1).reshape(2,1)*price - orders*np.array([[0.6],[0.8]])
profit

array([[127.699  ],
       [107.22505]])

In [52]:
np.sum(profit)

234.92404999999997

### Task 4

Write a function <code>sold_fun</code> to calculate the expected sold quantities. The input arguments are:
1. The order quantity as an one-dimensional array <code>order</code>.
2. The discrete distribution expressed as a two-dimensional array <code>distr</code>.

**Solution**:

In [55]:
def sold_fun(order, distr):
    orders = np.array([[430],[380]])
    price = np.array([[1],[1.15]])
    sales = np.minimum(distr[1:], orders)
    profit = np.sum(distr[0]*sales, axis =1).reshape(2,1)*price - orders*np.array([[0.6],[0.8]])
    
    return np.sum(profit)
    

In [56]:
sold_fun(np.array([430,380]), distr)

234.92404999999997